### ISSUE TITLE
Faq page

### ISSUE THREAD

**Issue by vws100** [ALPSim/alpsim.github.io#10]
Let's add links to our discord channel.  

I created a permanent link to the discord welcome channel:

https://discord.gg/JRNWnnva9g

Let's put this link in a few places for now:

1) A new FAQ page

At the top of the page put a link to the discord site with a statement about joining. 

Then, list some FAQs with some answers.  To get started, you can start with some trivial questions about installation and provide a link to here https://alps.comp-phys.com/install/   The undergrads can help with the FAQ page.

2) Put the discord link at the top of the installation page as well

3) The top right corner next to the GitHub symbol if possible.

**Comment by Ooolab** [comment]
The FAQs page has been added with links to discord and some questions.
