### ISSUE TITLE
Installation tab improvement 

### ISSUE THREAD

**Issue by vws100** [ALPSim/alpsim.github.io#12]
The Installation tab should be restructured.  There should be 2 sections as in the documentation tab (where there are 4 Sections: Models and methods, Alps libraries, API References, Publications) 

Title: Installing ALPS 
Brief Blurb: Instructions for installing ALPS on Mac/Linux. 

Section 1:  Precompiled ALPS installation 

Fill in instructions for using pyalps (including python requirements) 
https://www.piwheels.org/project/pyalps/

Section 2:  ALPS installation from sources

Use the instructions already on the website currently under the installation tab.
Update Python requirements

**Comment by Ooolab** [comment]
The installation pages have been updated.
