### ISSUE TITLE
Governance page update 

### ISSUE THREAD

**Issue by vws100** [ALPSim/alpsim.github.io#6]
Let's use this format for the governance website

https://gen3.org/governance/

ALPS Mission:

ALPS aims to house and distribute software for simulation of correlated quantum systems. 

ALPS Community Steering Committee:

Put pictures, names, titles, institutions of Adrian, Vito, Emanuel

**Comment by Ooolab** [comment]
The page is updated.

**Comment by vws100** [comment]
> The page is updated. 

Can you add our emails to the governance page?

**Comment by egull** [comment]
Sure! Do you want it linked somewhere or just plain text with the name? Mine would be egull@umich.edu. I guess on Friday we should discuss preferred ways of contacting us... Discord, email, bug reports, or other channels?

**Comment by vws100** [comment]
[like]  Scarola, Vito reacted to your message:
________________________________

**Comment by vws100** [comment]
I asked Fei to put our emails on the governance page because it says at the top to contact us.  

But yes, we'll have to figure out a way for 1) potential contributors to get in touch 2) users to ask questions and get help

**Comment by Ooolab** [comment]
Okay. Added email addresses to the page. Adrian and Vito: if you would like to use another email address, please let me know.
