### ISSUE TITLE
Organizing Tabs

### ISSUE THREAD

**Issue by vws100** [ALPSim/alpsim.github.io#7]
Rename this tab and make it the central Monte Carlo tab: Monte Carlo Simulations Using ALPS -> Monte Carlo

Let's move Monte Carlo stuff under the "Monte Carlo" tab.

1) Monte Carlo Simulation Directed Worm
2)QMC Tutorials

Under the Monte Carlo tab (formerly "Monte Carlo Simulations Using ALPS") let's sort the tab in a logical order:
-Which code to choose for your simulation
-QMC tutorials (Rename to Monte Carlo Tutorials) 
-MC-01a Autocorrelations 
-MC-01b Equilibration
etc.

There are several missing pages under the ALPSsize tab.  Let's delete these.

Under the Documentation Tab there is nothing under "Code Structure" or "Data Structure" were you planning on adding something there?  If not, let's remove things that we can't click on to go somewhere.

**Comment by optimizationLabIOS** [comment]
Done. Let me know if you think the page order should be different. Also removed the empty tabs.

**Comment by vws100** [comment]
> Done. Let me know if you think the page order should be different. Also removed the empty tabs. 

This tab does not have much yet:

https://alps.comp-phys.com/projects/

Let's hide it until we have something substantial to add there

**Comment by Ooolab** [comment]
Okay. Projects page is moved under tutorials page (at the bottom). The basic theory tab was removed. The ising model page is now under the spinmc page (some reorganization there).
