### ISSUE TITLE
Publication References 

### ISSUE THREAD

**Issue by vws100** [ALPSim/alpsim.github.io#8]
Under the documentation tab:

https://alps.comp-phys.com/documentation/

Let's add a button for a webpage that mentions the 4 ALPS papers and includes a link to the pdfs.  

The webpage can just be a publication list with title, authors, abstract, journal reference, link to journal pdf (the pdf should be housed on GitHub so that a click on the link downloads the pdf, no bouncing).  

Title: Matrix Product State applications for the ALPS project
Reference: Comput. Phys. Commun. 185, 3430 (2014)
Authors: Michele Dolfi, Bela Bauer, Sebastian Keller, Alexandr Kosenkov, Timothée Ewart, Adrian Kantian, Thierry Giamarchi, Matthias Troyer
Abstract: The density-matrix renormalization group method has become a standard computational approach to the low-energy physics as well as dynamics of low-dimensional quantum systems. In this paper, we present a new set of applications, available as part of the ALPS package, that provide an efficient and flexible implementation of these methods based on a matrix-product state (MPS) representation. Our applications implement, within the same framework, algorithms to variationally find the ground state and low-lying excited states as well as simulate the time evolution of arbitrary one-dimensional and two-dimensional models. Implementing the conservation of quantum numbers for generic Abelian symmetries, we achieve performance competitive with the best codes in the community. Example results are provided for (i) a model of itinerant fermions in one dimension and (ii) a model of quantum magnetism.

Title: The ALPS project release 2.0: Open source software for strongly correlated systems
Reference: J. Stat. Mech. (2011) P05001
Authors: B. Bauer, L. D. Carr, H.G. Evertz, A. Feiguin, J. Freire, S. Fuchs, L. Gamper, J. Gukelberger, E. Gull, S. Guertler, A. Hehn, R. Igarashi, S.V. Isakov, D. Koop, P.N. Ma, P. Mates, H. Matsuo, O. Parcollet, G. Pawlowski, J.D. Picon, L. Pollet, E. Santos, V.W. Scarola, U. Schollwöck, C. Silva, B. Surer, S. Todo, S. Trebst, M. Troyer, M.L. Wall, P. Werner, S. Wessel
Abstract: We present release 2.0 of the ALPS (Algorithms and Libraries for Physics Simulations) project, an open source software project to develop libraries and application programs for the simulation of strongly correlated quantum lattice models such as quantum magnets, lattice bosons, and strongly correlated fermion systems. The code development is centered on common XML and HDF5 data formats, libraries to simplify and speed up code development, common evaluation and plotting tools, and simulation programs. The programs enable non-experts to start carrying out serial or parallel numerical simulations by providing basic implementations of the important algorithms for quantum lattice models: classical and quantum Monte Carlo (QMC) using non-local updates, extended ensemble simulations, exact and full diagonalization (ED), the density matrix renormalization group (DMRG) both in a static version and a dynamic time-evolving block decimation (TEBD) code, and quantum Monte Carlo solvers for dynamical mean field theory (DMFT). The ALPS libraries provide a powerful framework for programers to develop their own applications, which, for instance, greatly simplify the steps of porting a serial code onto a parallel, distributed memory machine. Major changes in release 2.0 include the use of HDF5 for binary data, evaluation tools in Python, support for the Windows operating system, the use of CMake as build system and binary installation packages for Mac OS X and Windows, and integration with the VisTrails workflow provenance tool. The software is available from our web server at this http URL.

Title: The ALPS project release 1.3: open source software for strongly correlated systems
Reference: Journal of Magnetism and Magnetic Materials 310, 1187 (2007)
Authors: A.F. Albuquerque, F. Alet, P. Corboz, P. Dayal, A. Feiguin, S. Fuchs, L. Gamper, E. Gull, S. Guertler, A. Honecker, R. Igarashi, M. Koerner, A. Kozhevnikov, A. Laeuchli, S.R. Manmana, M. Matsumoto, I.P. McCulloch, F. Michel, R.M. Noack, G. Pawlowski, L. Pollet, T. Pruschke, U. Schollwock, S. Todo, S. Trebst, M. Troyer, P. Werner, S. Wessel

Abstract: We present release 1.3 of the ALPS (Algorithms and Libraries for Physics Simulations) project, an international open source software project to develop libraries and application programs for the simulation of strongly correlated quantum lattice models such as quantum magnets, lattice bosons, and strongly correlated fermion systems. Development is centered on common XML and binary data formats, on libraries to simplify and speed up code development, and on full-featured simulation programs. The programs enable non-experts to start carrying out numerical simulations by providing basic implementations of the important algorithms for quantum lattice models: classical and quantum Monte Carlo (QMC) using non-local updates, extended ensemble simulations, exact and full diagonalization (ED), as well as the density matrix renormalization group (DMRG). Changes in the new release include a DMRG program for interacting models, support for translation symmetries in the diagonalization programs, the ability to define custom measurement operators, and support for inhomogeneous systems, such as lattice models with traps. The software is available from our web server at this http URL .

Title: The ALPS project: open source software for strongly correlated systems
Reference: J. Phys. Soc. Jpn. Suppl. 74, 30 (2005)
Authors: F. Alet, P. Dayal, A. Grzesik, A. Honecker, M. Koerner, A. Laeuchli, S.R. Manmana, I.P. McCulloch, F. Michel, R.M. Noack, G. Schmid, U. Schollwoeck, F. Stoeckli, S. Todo, S. Trebst, M. Troyer, P. Werner, S. Wessel
Abstract: We present the ALPS (Algorithms and Libraries for Physics Simulations) project, an international open source software project to develop libraries and application programs for the simulation of strongly correlated quantum lattice models such as quantum magnets, lattice bosons, and strongly correlated fermion systems. Development is centered on common XML and binary data formats, on libraries to simplify and speed up code development, and on full-featured simulation programs. The programs enable non-experts to start carrying out numerical simulations by providing basic implementations of the important algorithms for quantum lattice models: classical and quantum Monte Carlo (QMC) using non-local updates, extended ensemble simulations, exact and full diagonalization (ED), as well as the density matrix renormalization group (DMRG). The software is available from our web server at this http URL.

**Comment by optimizationLabIOS** [comment]
The publication page is set up. Two papers were downloaded from the journal source. But the other two were from arXiv, since VT does not subscribe to these two journals' full text. Perhaps from Michigan's subscription?
