### ISSUE TITLE
blank tutorials 

### ISSUE THREAD

**Issue by vws100** [ALPSim/alpsim.github.io#9]
I noticed a few items missing from the tutorials pages.  The following are blank but I vaguely remember them existing at some point:
 
https://alps.comp-phys.com/tutorials/general/hardcoded/
https://alps.comp-phys.com/tutorials/general/tools/

Can you find these?

For the other blank tutorials under projects for undergrads, can you put "under construction" or something?

https://alps.comp-phys.com/tutorials/projects/

**Comment by Ooolab** [comment]
I can not find these pages, so I removed them for the moment.
